apiVersion: primehub.io/v1alpha1
kind: PhAppTemplate
metadata:
  name: vllm-soc
  namespace: hub
spec:
  name: vLLM-soc3
  version: soc
  description: vLLM is a high-throughput and memory-efficient serving engine for LLMs.
  docLink: https://github.com/vllm-project/vllm
  icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAYAAACOEfKtAAABg2lDQ1BJQ0MgcHJvZmlsZQAAKJF9kT1Iw0AcxV9TpVIqgnYQcchQneyiUhxrFYpQIdQKrTqYXPoFTQxJiouj4Fpw8GOx6uDirKuDqyAIfoA4OzgpukiJ/0sKLWI8OO7Hu3uPu3eA0KwxzepJAppum9l0SswXVsTQKyIII4QEBmVmGbOSlIHv+LpHgK93cZ7lf+7P0a8WLQYEROIkM0ybeJ04sWkbnPeJo6wiq8TnxBMmXZD4keuKx2+cyy4LPDNq5rJzxFFisdzFSheziqkRTxPHVE2nfCHvscp5i7NWq Dus3P2PfkLI0V9eYnrNEeRxgIWIUGEgjqqqMFGnFadFAtZ2k/5+Edcv0QuhVxVMHLMYwMaZNcP/ge/u7VKU5NeUiQF9L44zscYENoFWg3H+T52nNYJEHwGrvSOf6MJzHyS3uhosSNgYBu4uO5oyh5wuQMMPxmyKbtSkKZQKgHvZ/RNBWDoFgiver2193H6AOSoq8wNcHAIjJcpe83n3X3dvf17pt3fD5ogcrap9HCcAAAACXBIWXMAAAsTAAALEwEAmpwYAAAI3UlEQVR42u2ce4wX1RXHP/vmrbCLLhbXFwuCKY0YAppqWxcjqbRVC22jTaUajTG2Gh/xEYmJaahNk9pI22itprUmpa02mIiPvqS21ArVohaoisEQoOAKu7Ary8Lub/vHnEnvnjkz+/vNb2Z2JtlvMtmdmTv33Hvm3vP+DYxhDGMYwxjGEBN1KfZdA8wAzgEmAoeBUkbzmiR0TwF6gWNFezEnA08BR4EhYdxm4KKU6dYD3wb2Ct0hYD9wJ9BQFOa1Am87E3CPj4Evpbib1sjLsmg/mvKOSwS1wLMhE/CPA8CsFGhfF8E8fxdcn3cGLgMG1cAHjcn8VmRkUmiRraoZphn6X2BaXplXA7ysBnwIuAT4s7p+HJifIO17DeatAu42mHhrXhk421Ea/nG/3GsXbejeeyhBxfGu6nujKI0G4DV17/WEV39iuFkNtAeY6dx/Ut3fKZOvFouAAdX3lc79lere0ZRkcNV4Wg30j+r+pSlt43tUv/uAE5RV0KPafD1JrZlUP+eqaxvU+WbgoNp6CyP6awAa5W99xLa7QJ3/Q2Svj/3AdtXmvLwxsAVoVtdeV+cHgf+oa+4KPBFYDvwU2ATsEe/lIPAe8AJwH/ApZ+vXisfhYqM6HwK2qGtn5237nq3k0EDIIB9VW+l54HTgh0DnCPajaxa9BlwlMrZb3V9q0L1TtdmWNwYuVgM8LLJH4y6jXXeZjLOOd9WLGwTmGXSvUs/tSUiBJdOJBAtc9ANHjHb71PnkKum2q/M+Jf98dBnzbhTm54KBGqWQwR0q47ntwO+BN0QPNAFnARcCHSIrw3BMmGhdzzU61BbpDFldS0O24gCwXphUH+HpTBNPYndIP53AlDLo7gcm5ImBFxgu3MlGuxuMSe8Vw7cSi6AZeNzws3uBM432XzNkYEOeZGCXbD+fCRNECy8QF2+WmDo6HvgO8AUxUyrBAYmsbAW+58xjIrBWlMtu6Xc7cIZ6vkcM+dxghmhU7TJFadCPgDkJBDC+OwKdkii0KC9p1FEvb7tc86MEXJsQ7fHAPys0fx7KGwM/Kx5DuRP4F8mG2C8jOpiqj1eBk5IgnESIuwN4Bphq3OsXefSKDHqPKI37Y8i9KOwUxXIE+Lu4kQdFFk8y2s8EPiOav3c0V94SQ/YNyeBXiwIZzdjbJODzIvOsFbolxFrIBHND/NeXDK032qiTEJYlZv4kxnqmaJQtqQfz+GgMpgIsEDGix70q64HcYGyJdcLYvGORIXYOhxjgqWCCYbLsGk1ZEgPfMlbh6qyIf9Egfi3FQpNoancOW8moeuEpRfj9vDnmZeJqI6BxXtpEx4vN5RJ+kGLiRMOKuKPSTirNiZwEnOqc+2ZLEdGNlxpwsTBtBp6mvJc+gomipAzgVqBNvIbpKWn4N9T5WWmHs3RdyVHgwxHsxa/iBUrfAx6TN2/hE3hZuWV4eY1mEfZ+Vdc+CRo8Dbwo1yycA3xTaK8V1y4Mu9T5ZOHJQFrL/gqCxTpRWKPa/1XkqItm4AdUllzaIUzSC2C+8jb6xJULwzcMhZiqLXsZwcjz+JC2swnG4YaAzymjdocR6uqW1faS+LHbCMYXS3ildG4++mGD3qYIUXWLYcrUpsnAcxXBfsKT1CtCVs8SuX8RXiTb7Wut3J8gE6mRo04U2DXCkJJikM/EHxv0ukWGWviJavty2ppruuEGrQxpu5hg0c8HeEmfNoaX4W4Fzq9Abt+oxrFOrl9s0HwfGBeiQN9SbdedzcAavNoTl+iLERr++3gpRb/o59Ny71cMLzeL4wZe7DCxhJc4qsUrNvJpdopSCttNx9RcvpKF/XSvsY0XRjB8lmxLPwI8R4S7L0MtETAHuEnMpnUi7C3hfpN6Ef62nyeytiViXLrcrouEotQj4QyCxZKvhGwTC7c6z/0opI1f6drL/1OXljYd5wQ2+kVxlYMlxup7Mksr/jFDWD9TpjP+M6ILgQBuUxPcwfBiTRePOO2WlUF/FsHEfB9e1VdmmEmwqHtIApblBiMGR3CdbnPkWEtEuwcc+l8ug/4DxrgfjsuIuDbPXoJJoYEI78BFl0O7fQQvxg89RSXB5zr/HyqDvtVmZ9aO+IWGufDzMl+IG0b6A+GZwctFc/8tQr62OR5MT5nasPoRuRpZb3ZhuV4O3s914p11w9I4s445y4Lg30x10l15243G3O3X45Lh5f3f0k388r4c379L4i+9sL8s4mZ51m9S23C/z1X2Mv5mY+15i/4d4i5b/h61w8sX3k6H3a12N4wz1H+B5d53p516zYAAAAAElFTkSuFJ0=
  defaultEnvs:
  - name: HUGGING_FACE_HUB_TOKEN
    description: "Hugging Face API Token (Required for gated/private models like Llama 3)"
    defaultValue: ""
    optional: true
  - name: VLLM_MODEL
    description: "Hugging Face model name or local path"
    defaultValue: "meta-llama/Meta-Llama-3-8B-Instruct"
    optional: false
  - name: GPU_MEMORY_UTILIZATION
    description: "The fraction of GPU memory to be used for the model (0.0 - 1.0)"
    defaultValue: "0.90"
    optional: false
  template:
    spec:
      podTemplate:
        spec:
          containers:
          - name: vllm-soc3
            image: docker.io/vllm/vllm-openai:latest
            ports:
            - containerPort: 8000
              name: vllm-soc3
              protocol: TCP
            command: ["python3", "-m", "vllm.entrypoints.openai.api_server"]
            args:
            - "--model"
            - "$(VLLM_MODEL)"
            - "--host"
            - "0.0.0.0"
            - "--port"
            - "8000"
            - "--gpu-memory-utilization"
            - "$(GPU_MEMORY_UTILIZATION)"
            - "--trust-remote-code"
            volumeMounts:
            - mountPath: /root/.cache/huggingface
              name: model-cache
          volumes:
          - name: model-cache
            hostPath:
              path: $(PRIMEHUB_APP_ROOT)/huggingface_cache
              type: DirectoryOrCreate
      svcTemplate:
        spec:
          ports:
            - name: vllm-soc3
              port: 8000
              protocol: TCP
              targetPort: 8000
      httpPort: 8000
      rewrite: true
